// Catálogo de iconos lucide del motor (subconjunto CURADO, ~658 de los
// 1500 de la colección): los que ofrece el IconPicker (pestañas del CRM y
// cualquier campo `icon` del DSL) y los que la web sabe pintar por nombre
// (BlockTabs). El nombre guardado es el kebab-case de lucide (p. ej.
// `layout-grid`). Importados uno a uno para que Vite empaquete solo estos.
// GENERADO: ampliar es añadir nombres aquí (existen en @lucide/vue).
import type { Component } from 'vue'
import {
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Dices,
  Swords,
  Sword,
  Shield,
  ShieldHalf,
  ShieldCheck,
  ShieldAlert,
  ShieldPlus,
  ShieldOff,
  Crown,
  Gem,
  Trophy,
  Medal,
  Award,
  Target,
  Crosshair,
  Skull,
  Bomb,
  Flame,
  Zap,
  Wand,
  WandSparkles,
  Sparkles,
  Sparkle,
  Star,
  Heart,
  HeartCrack,
  HeartOff,
  Gamepad2,
  Joystick,
  Puzzle,
  Spade,
  Club,
  Diamond,
  Flag,
  FlagTriangleRight,
  Castle,
  Tent,
  Trees,
  Mountain,
  Sun,
  Moon,
  CloudLightning,
  Axe,
  Hammer,
  Pickaxe,
  Anvil,
  Scroll,
  ScrollText,
  Book,
  BookOpen,
  BookOpenText,
  Library,
  Key,
  KeyRound,
  Lock,
  LockOpen,
  LockKeyhole,
  Hourglass,
  Timer,
  Ghost,
  Bird,
  Cat,
  Dog,
  Rabbit,
  Rat,
  Fish,
  Bug,
  Snail,
  Squirrel,
  Turtle,
  Origami,
  Feather,
  Leaf,
  Clover,
  Flower,
  Flower2,
  Shell,
  Egg,
  Drumstick,
  Beef,
  Wheat,
  Apple,
  Cherry,
  Grape,
  Citrus,
  Pizza,
  Beer,
  Wine,
  Martini,
  Coffee,
  CupSoda,
  Utensils,
  UtensilsCrossed,
  Candy,
  CandyCane,
  Cake,
  Cookie,
  IceCreamCone,
  Lollipop,
  Layers,
  Layers2,
  SquareStack,
  Copy,
  CopyPlus,
  CopyCheck,
  GalleryHorizontal,
  GalleryVertical,
  GalleryThumbnails,
  GalleryHorizontalEnd,
  RectangleVertical,
  RectangleHorizontal,
  Square,
  SquareDashed,
  SquaresIntersect,
  WalletCards,
  IdCard,
  CreditCard,
  BookCopy,
  BookMarked,
  Bookmark,
  BookmarkCheck,
  BookmarkPlus,
  BookmarkX,
  Notebook,
  NotebookPen,
  NotebookTabs,
  StickyNote,
  Folder,
  FolderOpen,
  Archive,
  Package,
  PackageOpen,
  PackagePlus,
  Box,
  Boxes,
  ShoppingBag,
  ShoppingCart,
  Gift,
  User,
  UserRound,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  UserCog,
  UserPen,
  Users,
  UsersRound,
  UserRoundPlus,
  UserRoundCheck,
  UserRoundCog,
  Contact,
  ContactRound,
  Baby,
  PersonStanding,
  Accessibility,
  Hand,
  HandMetal,
  HandHeart,
  Handshake,
  HeartHandshake,
  Footprints,
  Eye,
  EyeOff,
  EyeClosed,
  Smile,
  Frown,
  Meh,
  Laugh,
  Angry,
  Brain,
  Ear,
  Speech,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Venus,
  Mars,
  House,
  HousePlus,
  Map,
  MapPin,
  MapPinned,
  MapPinPlus,
  MapPinCheck,
  Compass,
  Navigation,
  Navigation2,
  Route,
  Signpost,
  SignpostBig,
  Milestone,
  DoorOpen,
  DoorClosed,
  LogIn,
  LogOut,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowUpRight,
  ArrowDownRight,
  ArrowLeftRight,
  ArrowUpDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ChevronsDown,
  Move,
  MoveHorizontal,
  MoveVertical,
  CornerDownRight,
  CornerUpLeft,
  Undo,
  Redo,
  Undo2,
  Redo2,
  RotateCcw,
  RotateCw,
  RefreshCw,
  RefreshCcw,
  Repeat,
  Shuffle,
  ExternalLink,
  Link,
  Link2,
  Unlink,
  Anchor,
  Menu,
  Grip,
  GripVertical,
  GripHorizontal,
  Ellipsis,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelsTopLeft,
  PanelsLeftBottom,
  LayoutGrid,
  LayoutList,
  LayoutDashboard,
  LayoutTemplate,
  LayoutPanelLeft,
  Columns2,
  Columns3,
  Rows2,
  Rows3,
  Table,
  Table2,
  Plus,
  Minus,
  X,
  Check,
  CheckCheck,
  CirclePlus,
  CircleMinus,
  CircleX,
  CircleCheck,
  CircleAlert,
  CircleDot,
  CircleOff,
  SquarePlus,
  SquareMinus,
  SquareX,
  SquareCheck,
  SquarePen,
  Pen,
  Pencil,
  PencilLine,
  PenTool,
  Highlighter,
  Eraser,
  Trash,
  Trash2,
  Save,
  Download,
  Upload,
  CloudDownload,
  CloudUpload,
  Share,
  Share2,
  Send,
  SendHorizontal,
  Forward,
  Reply,
  ReplyAll,
  Printer,
  Scan,
  ScanLine,
  Search,
  SearchCheck,
  SearchX,
  ZoomIn,
  ZoomOut,
  SlidersHorizontal,
  SlidersVertical,
  Settings,
  Settings2,
  Cog,
  Wrench,
  ToolCase,
  Power,
  PowerOff,
  Play,
  Pause,
  SquareSquare,
  SkipBack,
  SkipForward,
  StepBack,
  StepForward,
  FastForward,
  Rewind,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Bell,
  BellRing,
  BellOff,
  BellPlus,
  Pin,
  PinOff,
  Paperclip,
  Scissors,
  Clipboard,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardPaste,
  Maximize,
  Minimize,
  Maximize2,
  Minimize2,
  Expand,
  Shrink,
  Fullscreen,
  File,
  FileText,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  FileSearch,
  FileDown,
  FileUp,
  FileImage,
  FileCode,
  FileSpreadsheet,
  FileBadge,
  Files,
  Newspaper,
  TextQuote,
  Quote,
  Heading,
  Heading1,
  Heading2,
  Heading3,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  List,
  ListOrdered,
  ListChecks,
  ListTodo,
  ListTree,
  ListPlus,
  ListX,
  ListFilter,
  Type,
  ALargeSmall,
  CaseSensitive,
  CaseUpper,
  CaseLower,
  Pilcrow,
  Hash,
  AtSign,
  Languages,
  SpellCheck,
  BookA,
  Captions,
  Image,
  Images,
  ImagePlus,
  ImageOff,
  Camera,
  CameraOff,
  Video,
  VideoOff,
  Film,
  Clapperboard,
  Music,
  Music2,
  Music4,
  Disc,
  Disc3,
  Radio,
  Tv,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Palette,
  Paintbrush,
  PaintbrushVertical,
  PaintBucket,
  PaintRoller,
  Brush,
  Pipette,
  Droplet,
  Droplets,
  Contrast,
  SunMedium,
  SunDim,
  MoonStar,
  Lightbulb,
  LightbulbOff,
  Lamp,
  Flashlight,
  Shapes,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  Circle,
  Blend,
  Component as ComponentIcon,
  Frame,
  Crop,
  Ruler,
  RulerDimensionLine,
  PenLine,
  Spline,
  VectorSquare,
  ScanEye,
  Glasses,
  Calendar,
  CalendarDays,
  CalendarCheck,
  CalendarPlus,
  CalendarX,
  CalendarClock,
  CalendarHeart,
  CalendarRange,
  CalendarSearch,
  Clock,
  Clock1,
  Clock3,
  Clock6,
  Clock9,
  Clock12,
  AlarmClock,
  AlarmClockCheck,
  TimerOff,
  TimerReset,
  History,
  Watch,
  Sunrise,
  Sunset,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudSun,
  CloudMoon,
  CloudFog,
  Wind,
  Snowflake,
  Thermometer,
  ThermometerSun,
  Umbrella,
  Rainbow,
  Tornado,
  Haze,
  Mail,
  MailOpen,
  MailPlus,
  MailCheck,
  MailX,
  Inbox,
  MessageCircleMore,
  MessageSquareMore,
  MessageSquareText,
  Phone,
  PhoneCall,
  PhoneOff,
  Voicemail,
  Rss,
  Wifi,
  WifiOff,
  Bluetooth,
  Globe,
  GlobeLock,
  Earth,
  Network,
  Server,
  Database,
  CloudOff,
  HardDrive,
  Cpu,
  MemoryStick,
  Usb,
  Plug,
  PlugZap,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  Signal,
  SignalHigh,
  SignalLow,
  Antenna,
  Satellite,
  SatelliteDish,
  RadioTower,
  Webhook,
  Code,
  CodeXml,
  Terminal,
  Braces,
  Brackets,
  BugOff,
  GitBranch,
  GitCommitHorizontal,
  GitMerge,
  GitPullRequest,
  Info,
  TriangleAlert,
  OctagonAlert,
  Badge,
  BadgeCheck,
  BadgeAlert,
  BadgeInfo,
  BadgeX,
  BadgePlus,
  BadgeMinus,
  BadgeDollarSign,
  BadgePercent,
  Ban,
  CircleCheckBig,
  Loader,
  LoaderCircle,
  Activity,
  HeartPulse,
  Gauge,
  ThumbsUp,
  ThumbsDown,
  StarHalf,
  StarOff,
  ShieldEllipsis,
  Megaphone,
  Siren,
  Construction,
  TrafficCone,
  Coins,
  Banknote,
  Wallet,
  PiggyBank,
  Receipt,
  ReceiptText,
  Ticket,
  TicketPercent,
  Tickets,
  Tag,
  Tags,
  Percent,
  DollarSign,
  Euro,
  PoundSterling,
  Bitcoin,
  Calculator,
  Scale,
  Scale3d,
  Weight,
  ChartBar,
  ChartBarBig,
  ChartColumn,
  ChartLine,
  ChartPie,
  ChartArea,
  ChartNoAxesColumn,
  ChartSpline,
  TrendingUp,
  TrendingDown,
  Sigma,
  Pi,
  Infinity,
  Binary,
  Divide,
  Equal,
  Backpack,
  Briefcase,
  Luggage,
  Shirt,
  Magnet,
  LampDesk,
  Bed,
  Sofa,
  Armchair,
  Bath,
  Fence,
  Warehouse,
  Factory,
  Building,
  Building2,
  School,
  Church,
  Hospital,
  Store,
  Landmark,
  Bus,
  Car,
  Truck,
  TramFront,
  Plane,
  Rocket,
  Ship,
  Sailboat,
  Bike,
  Fuel,
  CarFront,
  Cone,
  Cylinder,
  Cuboid,
  Pyramid,
  Torus,
  FlaskConical,
  FlaskRound,
  TestTube,
  TestTubes,
  Microscope,
  Telescope,
  Dna,
  Atom,
  Orbit,
  Syringe,
  Pill,
  Stethoscope,
  Bandage,
  Cross,
  Recycle,
  Sprout,
  TreePine,
  TreeDeciduous,
  TreePalm,
  MountainSnow,
} from '@lucide/vue'

export interface IconCategory {
  key: string
  /** Etiqueta en castellano (el admin puede traducirla: iconCategories.<key>). */
  label: string
  icons: string[]
}

/** Categorías del catálogo, en el orden del picker. */
export const ICON_CATALOG: IconCategory[] = [
  {
    key: 'juego',
    label: 'Juego',
    icons: [
      'dice-1',
      'dice-2',
      'dice-3',
      'dice-4',
      'dice-5',
      'dice-6',
      'dices',
      'swords',
      'sword',
      'shield',
      'shield-half',
      'shield-check',
      'shield-alert',
      'shield-plus',
      'shield-off',
      'crown',
      'gem',
      'trophy',
      'medal',
      'award',
      'target',
      'crosshair',
      'skull',
      'bomb',
      'flame',
      'zap',
      'wand',
      'wand-sparkles',
      'sparkles',
      'sparkle',
      'star',
      'heart',
      'heart-crack',
      'heart-off',
      'gamepad-2',
      'joystick',
      'puzzle',
      'spade',
      'club',
      'diamond',
      'flag',
      'flag-triangle-right',
      'castle',
      'tent',
      'trees',
      'mountain',
      'sun',
      'moon',
      'cloud-lightning',
      'axe',
      'hammer',
      'pickaxe',
      'anvil',
      'scroll',
      'scroll-text',
      'book',
      'book-open',
      'book-open-text',
      'library',
      'key',
      'key-round',
      'lock',
      'lock-open',
      'lock-keyhole',
      'hourglass',
      'timer',
      'ghost',
      'bird',
      'cat',
      'dog',
      'rabbit',
      'rat',
      'fish',
      'bug',
      'snail',
      'squirrel',
      'turtle',
      'origami',
      'feather',
      'leaf',
      'clover',
      'flower',
      'flower-2',
      'shell',
      'egg',
      'drumstick',
      'beef',
      'wheat',
      'apple',
      'cherry',
      'grape',
      'citrus',
      'pizza',
      'beer',
      'wine',
      'martini',
      'coffee',
      'cup-soda',
      'utensils',
      'utensils-crossed',
      'candy',
      'candy-cane',
      'cake',
      'cookie',
      'ice-cream-cone',
      'lollipop',
    ],
  },
  {
    key: 'cartas',
    label: 'Cartas y mazos',
    icons: [
      'layers',
      'layers-2',
      'square-stack',
      'copy',
      'copy-plus',
      'copy-check',
      'gallery-horizontal',
      'gallery-vertical',
      'gallery-thumbnails',
      'gallery-horizontal-end',
      'rectangle-vertical',
      'rectangle-horizontal',
      'square',
      'square-dashed',
      'squares-intersect',
      'wallet-cards',
      'id-card',
      'credit-card',
      'book-copy',
      'book-marked',
      'bookmark',
      'bookmark-check',
      'bookmark-plus',
      'bookmark-x',
      'notebook',
      'notebook-pen',
      'notebook-tabs',
      'sticky-note',
      'folder',
      'folder-open',
      'archive',
      'package',
      'package-open',
      'package-plus',
      'box',
      'boxes',
      'shopping-bag',
      'shopping-cart',
      'gift',
    ],
  },
  {
    key: 'personas',
    label: 'Personas',
    icons: [
      'user',
      'user-round',
      'user-plus',
      'user-minus',
      'user-check',
      'user-x',
      'user-cog',
      'user-pen',
      'users',
      'users-round',
      'user-round-plus',
      'user-round-check',
      'user-round-cog',
      'contact',
      'contact-round',
      'baby',
      'person-standing',
      'accessibility',
      'hand',
      'hand-metal',
      'hand-heart',
      'handshake',
      'heart-handshake',
      'footprints',
      'eye',
      'eye-off',
      'eye-closed',
      'smile',
      'frown',
      'meh',
      'laugh',
      'angry',
      'brain',
      'ear',
      'speech',
      'message-circle',
      'message-square',
      'messages-square',
      'venus',
      'mars',
    ],
  },
  {
    key: 'navegacion',
    label: 'Navegación',
    icons: [
      'house',
      'house-plus',
      'map',
      'map-pin',
      'map-pinned',
      'map-pin-plus',
      'map-pin-check',
      'compass',
      'navigation',
      'navigation-2',
      'route',
      'signpost',
      'signpost-big',
      'milestone',
      'door-open',
      'door-closed',
      'log-in',
      'log-out',
      'arrow-left',
      'arrow-right',
      'arrow-up',
      'arrow-down',
      'arrow-up-right',
      'arrow-down-right',
      'arrow-left-right',
      'arrow-up-down',
      'chevron-left',
      'chevron-right',
      'chevron-up',
      'chevron-down',
      'chevrons-left',
      'chevrons-right',
      'chevrons-up',
      'chevrons-down',
      'move',
      'move-horizontal',
      'move-vertical',
      'corner-down-right',
      'corner-up-left',
      'undo',
      'redo',
      'undo-2',
      'redo-2',
      'rotate-ccw',
      'rotate-cw',
      'refresh-cw',
      'refresh-ccw',
      'repeat',
      'shuffle',
      'external-link',
      'link',
      'link-2',
      'unlink',
      'anchor',
      'menu',
      'grip',
      'grip-vertical',
      'grip-horizontal',
      'ellipsis',
      'panel-left',
      'panel-right',
      'panel-top',
      'panels-top-left',
      'panels-left-bottom',
      'layout-grid',
      'layout-list',
      'layout-dashboard',
      'layout-template',
      'layout-panel-left',
      'columns-2',
      'columns-3',
      'rows-2',
      'rows-3',
      'table',
      'table-2',
    ],
  },
  {
    key: 'acciones',
    label: 'Acciones',
    icons: [
      'plus',
      'minus',
      'x',
      'check',
      'check-check',
      'circle-plus',
      'circle-minus',
      'circle-x',
      'circle-check',
      'circle-alert',
      'circle-dot',
      'circle-off',
      'square-plus',
      'square-minus',
      'square-x',
      'square-check',
      'square-pen',
      'pen',
      'pencil',
      'pencil-line',
      'pen-tool',
      'highlighter',
      'eraser',
      'trash',
      'trash-2',
      'save',
      'download',
      'upload',
      'cloud-download',
      'cloud-upload',
      'share',
      'share-2',
      'send',
      'send-horizontal',
      'forward',
      'reply',
      'reply-all',
      'printer',
      'scan',
      'scan-line',
      'search',
      'search-check',
      'search-x',
      'zoom-in',
      'zoom-out',
      'sliders-horizontal',
      'sliders-vertical',
      'settings',
      'settings-2',
      'cog',
      'wrench',
      'tool-case',
      'power',
      'power-off',
      'play',
      'pause',
      'square-square',
      'skip-back',
      'skip-forward',
      'step-back',
      'step-forward',
      'fast-forward',
      'rewind',
      'volume',
      'volume-1',
      'volume-2',
      'volume-x',
      'mic',
      'mic-off',
      'bell',
      'bell-ring',
      'bell-off',
      'bell-plus',
      'pin',
      'pin-off',
      'paperclip',
      'scissors',
      'clipboard',
      'clipboard-check',
      'clipboard-copy',
      'clipboard-list',
      'clipboard-paste',
      'maximize',
      'minimize',
      'maximize-2',
      'minimize-2',
      'expand',
      'shrink',
      'fullscreen',
    ],
  },
  {
    key: 'documentos',
    label: 'Documentos y texto',
    icons: [
      'file',
      'file-text',
      'file-plus',
      'file-minus',
      'file-check',
      'file-x',
      'file-search',
      'file-down',
      'file-up',
      'file-image',
      'file-code',
      'file-spreadsheet',
      'file-badge',
      'files',
      'newspaper',
      'text-quote',
      'quote',
      'heading',
      'heading-1',
      'heading-2',
      'heading-3',
      'bold',
      'italic',
      'underline',
      'strikethrough',
      'list',
      'list-ordered',
      'list-checks',
      'list-todo',
      'list-tree',
      'list-plus',
      'list-x',
      'list-filter',
      'type',
      'a-large-small',
      'case-sensitive',
      'case-upper',
      'case-lower',
      'pilcrow',
      'hash',
      'at-sign',
      'languages',
      'spell-check',
      'book-a',
      'captions',
    ],
  },
  {
    key: 'multimedia',
    label: 'Multimedia y diseño',
    icons: [
      'image',
      'images',
      'image-plus',
      'image-off',
      'camera',
      'camera-off',
      'video',
      'video-off',
      'film',
      'clapperboard',
      'music',
      'music-2',
      'music-4',
      'disc',
      'disc-3',
      'radio',
      'tv',
      'monitor',
      'smartphone',
      'tablet',
      'laptop',
      'palette',
      'paintbrush',
      'paintbrush-vertical',
      'paint-bucket',
      'paint-roller',
      'brush',
      'pipette',
      'droplet',
      'droplets',
      'contrast',
      'sun-medium',
      'sun-dim',
      'moon-star',
      'lightbulb',
      'lightbulb-off',
      'lamp',
      'flashlight',
      'shapes',
      'triangle',
      'hexagon',
      'octagon',
      'pentagon',
      'circle',
      'blend',
      'component',
      'frame',
      'crop',
      'ruler',
      'ruler-dimension-line',
      'pen-line',
      'spline',
      'vector-square',
      'scan-eye',
      'glasses',
    ],
  },
  {
    key: 'tiempo',
    label: 'Tiempo y calendario',
    icons: [
      'calendar',
      'calendar-days',
      'calendar-check',
      'calendar-plus',
      'calendar-x',
      'calendar-clock',
      'calendar-heart',
      'calendar-range',
      'calendar-search',
      'clock',
      'clock-1',
      'clock-3',
      'clock-6',
      'clock-9',
      'clock-12',
      'alarm-clock',
      'alarm-clock-check',
      'timer-off',
      'timer-reset',
      'history',
      'watch',
      'sunrise',
      'sunset',
      'cloud',
      'cloud-rain',
      'cloud-snow',
      'cloud-sun',
      'cloud-moon',
      'cloud-fog',
      'wind',
      'snowflake',
      'thermometer',
      'thermometer-sun',
      'umbrella',
      'rainbow',
      'tornado',
      'haze',
    ],
  },
  {
    key: 'comunicacion',
    label: 'Comunicación y red',
    icons: [
      'mail',
      'mail-open',
      'mail-plus',
      'mail-check',
      'mail-x',
      'inbox',
      'message-circle-more',
      'message-square-more',
      'message-square-text',
      'phone',
      'phone-call',
      'phone-off',
      'voicemail',
      'rss',
      'wifi',
      'wifi-off',
      'bluetooth',
      'globe',
      'globe-lock',
      'earth',
      'network',
      'server',
      'database',
      'cloud-off',
      'hard-drive',
      'cpu',
      'memory-stick',
      'usb',
      'plug',
      'plug-zap',
      'battery',
      'battery-charging',
      'battery-full',
      'battery-low',
      'signal',
      'signal-high',
      'signal-low',
      'antenna',
      'satellite',
      'satellite-dish',
      'radio-tower',
      'webhook',
      'code',
      'code-xml',
      'terminal',
      'braces',
      'brackets',
      'bug-off',
      'git-branch',
      'git-commit-horizontal',
      'git-merge',
      'git-pull-request',
    ],
  },
  {
    key: 'estado',
    label: 'Estado y avisos',
    icons: [
      'info',
      'triangle-alert',
      'octagon-alert',
      'badge',
      'badge-check',
      'badge-alert',
      'badge-info',
      'badge-x',
      'badge-plus',
      'badge-minus',
      'badge-dollar-sign',
      'badge-percent',
      'ban',
      'circle-check-big',
      'loader',
      'loader-circle',
      'activity',
      'heart-pulse',
      'gauge',
      'thumbs-up',
      'thumbs-down',
      'star-half',
      'star-off',
      'shield-ellipsis',
      'megaphone',
      'siren',
      'construction',
      'traffic-cone',
    ],
  },
  {
    key: 'comercio',
    label: 'Comercio y números',
    icons: [
      'coins',
      'banknote',
      'wallet',
      'piggy-bank',
      'receipt',
      'receipt-text',
      'ticket',
      'ticket-percent',
      'tickets',
      'tag',
      'tags',
      'percent',
      'dollar-sign',
      'euro',
      'pound-sterling',
      'bitcoin',
      'calculator',
      'scale',
      'scale-3d',
      'weight',
      'chart-bar',
      'chart-bar-big',
      'chart-column',
      'chart-line',
      'chart-pie',
      'chart-area',
      'chart-no-axes-column',
      'chart-spline',
      'trending-up',
      'trending-down',
      'sigma',
      'pi',
      'infinity',
      'binary',
      'divide',
      'equal',
    ],
  },
  {
    key: 'objetos',
    label: 'Objetos',
    icons: [
      'backpack',
      'briefcase',
      'luggage',
      'shirt',
      'magnet',
      'lamp-desk',
      'bed',
      'sofa',
      'armchair',
      'bath',
      'fence',
      'warehouse',
      'factory',
      'building',
      'building-2',
      'school',
      'church',
      'hospital',
      'store',
      'landmark',
      'bus',
      'car',
      'truck',
      'tram-front',
      'plane',
      'rocket',
      'ship',
      'sailboat',
      'bike',
      'fuel',
      'car-front',
      'cone',
      'cylinder',
      'cuboid',
      'pyramid',
      'torus',
      'flask-conical',
      'flask-round',
      'test-tube',
      'test-tubes',
      'microscope',
      'telescope',
      'dna',
      'atom',
      'orbit',
      'syringe',
      'pill',
      'stethoscope',
      'bandage',
      'cross',
      'recycle',
      'sprout',
      'tree-pine',
      'tree-deciduous',
      'tree-palm',
      'mountain-snow',
    ],
  },
]

/** Nombre lucide => componente Vue. */
export const iconComponents: Record<string, Component> = {
  'dice-1': Dice1,
  'dice-2': Dice2,
  'dice-3': Dice3,
  'dice-4': Dice4,
  'dice-5': Dice5,
  'dice-6': Dice6,
  dices: Dices,
  swords: Swords,
  sword: Sword,
  shield: Shield,
  'shield-half': ShieldHalf,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  'shield-plus': ShieldPlus,
  'shield-off': ShieldOff,
  crown: Crown,
  gem: Gem,
  trophy: Trophy,
  medal: Medal,
  award: Award,
  target: Target,
  crosshair: Crosshair,
  skull: Skull,
  bomb: Bomb,
  flame: Flame,
  zap: Zap,
  wand: Wand,
  'wand-sparkles': WandSparkles,
  sparkles: Sparkles,
  sparkle: Sparkle,
  star: Star,
  heart: Heart,
  'heart-crack': HeartCrack,
  'heart-off': HeartOff,
  'gamepad-2': Gamepad2,
  joystick: Joystick,
  puzzle: Puzzle,
  spade: Spade,
  club: Club,
  diamond: Diamond,
  flag: Flag,
  'flag-triangle-right': FlagTriangleRight,
  castle: Castle,
  tent: Tent,
  trees: Trees,
  mountain: Mountain,
  sun: Sun,
  moon: Moon,
  'cloud-lightning': CloudLightning,
  axe: Axe,
  hammer: Hammer,
  pickaxe: Pickaxe,
  anvil: Anvil,
  scroll: Scroll,
  'scroll-text': ScrollText,
  book: Book,
  'book-open': BookOpen,
  'book-open-text': BookOpenText,
  library: Library,
  key: Key,
  'key-round': KeyRound,
  lock: Lock,
  'lock-open': LockOpen,
  'lock-keyhole': LockKeyhole,
  hourglass: Hourglass,
  timer: Timer,
  ghost: Ghost,
  bird: Bird,
  cat: Cat,
  dog: Dog,
  rabbit: Rabbit,
  rat: Rat,
  fish: Fish,
  bug: Bug,
  snail: Snail,
  squirrel: Squirrel,
  turtle: Turtle,
  origami: Origami,
  feather: Feather,
  leaf: Leaf,
  clover: Clover,
  flower: Flower,
  'flower-2': Flower2,
  shell: Shell,
  egg: Egg,
  drumstick: Drumstick,
  beef: Beef,
  wheat: Wheat,
  apple: Apple,
  cherry: Cherry,
  grape: Grape,
  citrus: Citrus,
  pizza: Pizza,
  beer: Beer,
  wine: Wine,
  martini: Martini,
  coffee: Coffee,
  'cup-soda': CupSoda,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  candy: Candy,
  'candy-cane': CandyCane,
  cake: Cake,
  cookie: Cookie,
  'ice-cream-cone': IceCreamCone,
  lollipop: Lollipop,
  layers: Layers,
  'layers-2': Layers2,
  'square-stack': SquareStack,
  copy: Copy,
  'copy-plus': CopyPlus,
  'copy-check': CopyCheck,
  'gallery-horizontal': GalleryHorizontal,
  'gallery-vertical': GalleryVertical,
  'gallery-thumbnails': GalleryThumbnails,
  'gallery-horizontal-end': GalleryHorizontalEnd,
  'rectangle-vertical': RectangleVertical,
  'rectangle-horizontal': RectangleHorizontal,
  square: Square,
  'square-dashed': SquareDashed,
  'squares-intersect': SquaresIntersect,
  'wallet-cards': WalletCards,
  'id-card': IdCard,
  'credit-card': CreditCard,
  'book-copy': BookCopy,
  'book-marked': BookMarked,
  bookmark: Bookmark,
  'bookmark-check': BookmarkCheck,
  'bookmark-plus': BookmarkPlus,
  'bookmark-x': BookmarkX,
  notebook: Notebook,
  'notebook-pen': NotebookPen,
  'notebook-tabs': NotebookTabs,
  'sticky-note': StickyNote,
  folder: Folder,
  'folder-open': FolderOpen,
  archive: Archive,
  package: Package,
  'package-open': PackageOpen,
  'package-plus': PackagePlus,
  box: Box,
  boxes: Boxes,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  gift: Gift,
  user: User,
  'user-round': UserRound,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'user-check': UserCheck,
  'user-x': UserX,
  'user-cog': UserCog,
  'user-pen': UserPen,
  users: Users,
  'users-round': UsersRound,
  'user-round-plus': UserRoundPlus,
  'user-round-check': UserRoundCheck,
  'user-round-cog': UserRoundCog,
  contact: Contact,
  'contact-round': ContactRound,
  baby: Baby,
  'person-standing': PersonStanding,
  accessibility: Accessibility,
  hand: Hand,
  'hand-metal': HandMetal,
  'hand-heart': HandHeart,
  handshake: Handshake,
  'heart-handshake': HeartHandshake,
  footprints: Footprints,
  eye: Eye,
  'eye-off': EyeOff,
  'eye-closed': EyeClosed,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  laugh: Laugh,
  angry: Angry,
  brain: Brain,
  ear: Ear,
  speech: Speech,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'messages-square': MessagesSquare,
  venus: Venus,
  mars: Mars,
  house: House,
  'house-plus': HousePlus,
  map: Map,
  'map-pin': MapPin,
  'map-pinned': MapPinned,
  'map-pin-plus': MapPinPlus,
  'map-pin-check': MapPinCheck,
  compass: Compass,
  navigation: Navigation,
  'navigation-2': Navigation2,
  route: Route,
  signpost: Signpost,
  'signpost-big': SignpostBig,
  milestone: Milestone,
  'door-open': DoorOpen,
  'door-closed': DoorClosed,
  'log-in': LogIn,
  'log-out': LogOut,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-right': ArrowDownRight,
  'arrow-left-right': ArrowLeftRight,
  'arrow-up-down': ArrowUpDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'chevrons-up': ChevronsUp,
  'chevrons-down': ChevronsDown,
  move: Move,
  'move-horizontal': MoveHorizontal,
  'move-vertical': MoveVertical,
  'corner-down-right': CornerDownRight,
  'corner-up-left': CornerUpLeft,
  undo: Undo,
  redo: Redo,
  'undo-2': Undo2,
  'redo-2': Redo2,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  'refresh-cw': RefreshCw,
  'refresh-ccw': RefreshCcw,
  repeat: Repeat,
  shuffle: Shuffle,
  'external-link': ExternalLink,
  link: Link,
  'link-2': Link2,
  unlink: Unlink,
  anchor: Anchor,
  menu: Menu,
  grip: Grip,
  'grip-vertical': GripVertical,
  'grip-horizontal': GripHorizontal,
  ellipsis: Ellipsis,
  'panel-left': PanelLeft,
  'panel-right': PanelRight,
  'panel-top': PanelTop,
  'panels-top-left': PanelsTopLeft,
  'panels-left-bottom': PanelsLeftBottom,
  'layout-grid': LayoutGrid,
  'layout-list': LayoutList,
  'layout-dashboard': LayoutDashboard,
  'layout-template': LayoutTemplate,
  'layout-panel-left': LayoutPanelLeft,
  'columns-2': Columns2,
  'columns-3': Columns3,
  'rows-2': Rows2,
  'rows-3': Rows3,
  table: Table,
  'table-2': Table2,
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  'check-check': CheckCheck,
  'circle-plus': CirclePlus,
  'circle-minus': CircleMinus,
  'circle-x': CircleX,
  'circle-check': CircleCheck,
  'circle-alert': CircleAlert,
  'circle-dot': CircleDot,
  'circle-off': CircleOff,
  'square-plus': SquarePlus,
  'square-minus': SquareMinus,
  'square-x': SquareX,
  'square-check': SquareCheck,
  'square-pen': SquarePen,
  pen: Pen,
  pencil: Pencil,
  'pencil-line': PencilLine,
  'pen-tool': PenTool,
  highlighter: Highlighter,
  eraser: Eraser,
  trash: Trash,
  'trash-2': Trash2,
  save: Save,
  download: Download,
  upload: Upload,
  'cloud-download': CloudDownload,
  'cloud-upload': CloudUpload,
  share: Share,
  'share-2': Share2,
  send: Send,
  'send-horizontal': SendHorizontal,
  forward: Forward,
  reply: Reply,
  'reply-all': ReplyAll,
  printer: Printer,
  scan: Scan,
  'scan-line': ScanLine,
  search: Search,
  'search-check': SearchCheck,
  'search-x': SearchX,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  'sliders-horizontal': SlidersHorizontal,
  'sliders-vertical': SlidersVertical,
  settings: Settings,
  'settings-2': Settings2,
  cog: Cog,
  wrench: Wrench,
  'tool-case': ToolCase,
  power: Power,
  'power-off': PowerOff,
  play: Play,
  pause: Pause,
  'square-square': SquareSquare,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  'step-back': StepBack,
  'step-forward': StepForward,
  'fast-forward': FastForward,
  rewind: Rewind,
  volume: Volume,
  'volume-1': Volume1,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  mic: Mic,
  'mic-off': MicOff,
  bell: Bell,
  'bell-ring': BellRing,
  'bell-off': BellOff,
  'bell-plus': BellPlus,
  pin: Pin,
  'pin-off': PinOff,
  paperclip: Paperclip,
  scissors: Scissors,
  clipboard: Clipboard,
  'clipboard-check': ClipboardCheck,
  'clipboard-copy': ClipboardCopy,
  'clipboard-list': ClipboardList,
  'clipboard-paste': ClipboardPaste,
  maximize: Maximize,
  minimize: Minimize,
  'maximize-2': Maximize2,
  'minimize-2': Minimize2,
  expand: Expand,
  shrink: Shrink,
  fullscreen: Fullscreen,
  file: File,
  'file-text': FileText,
  'file-plus': FilePlus,
  'file-minus': FileMinus,
  'file-check': FileCheck,
  'file-x': FileX,
  'file-search': FileSearch,
  'file-down': FileDown,
  'file-up': FileUp,
  'file-image': FileImage,
  'file-code': FileCode,
  'file-spreadsheet': FileSpreadsheet,
  'file-badge': FileBadge,
  files: Files,
  newspaper: Newspaper,
  'text-quote': TextQuote,
  quote: Quote,
  heading: Heading,
  'heading-1': Heading1,
  'heading-2': Heading2,
  'heading-3': Heading3,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  list: List,
  'list-ordered': ListOrdered,
  'list-checks': ListChecks,
  'list-todo': ListTodo,
  'list-tree': ListTree,
  'list-plus': ListPlus,
  'list-x': ListX,
  'list-filter': ListFilter,
  type: Type,
  'a-large-small': ALargeSmall,
  'case-sensitive': CaseSensitive,
  'case-upper': CaseUpper,
  'case-lower': CaseLower,
  pilcrow: Pilcrow,
  hash: Hash,
  'at-sign': AtSign,
  languages: Languages,
  'spell-check': SpellCheck,
  'book-a': BookA,
  captions: Captions,
  image: Image,
  images: Images,
  'image-plus': ImagePlus,
  'image-off': ImageOff,
  camera: Camera,
  'camera-off': CameraOff,
  video: Video,
  'video-off': VideoOff,
  film: Film,
  clapperboard: Clapperboard,
  music: Music,
  'music-2': Music2,
  'music-4': Music4,
  disc: Disc,
  'disc-3': Disc3,
  radio: Radio,
  tv: Tv,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  palette: Palette,
  paintbrush: Paintbrush,
  'paintbrush-vertical': PaintbrushVertical,
  'paint-bucket': PaintBucket,
  'paint-roller': PaintRoller,
  brush: Brush,
  pipette: Pipette,
  droplet: Droplet,
  droplets: Droplets,
  contrast: Contrast,
  'sun-medium': SunMedium,
  'sun-dim': SunDim,
  'moon-star': MoonStar,
  lightbulb: Lightbulb,
  'lightbulb-off': LightbulbOff,
  lamp: Lamp,
  flashlight: Flashlight,
  shapes: Shapes,
  triangle: Triangle,
  hexagon: Hexagon,
  octagon: Octagon,
  pentagon: Pentagon,
  circle: Circle,
  blend: Blend,
  component: ComponentIcon,
  frame: Frame,
  crop: Crop,
  ruler: Ruler,
  'ruler-dimension-line': RulerDimensionLine,
  'pen-line': PenLine,
  spline: Spline,
  'vector-square': VectorSquare,
  'scan-eye': ScanEye,
  glasses: Glasses,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  'calendar-check': CalendarCheck,
  'calendar-plus': CalendarPlus,
  'calendar-x': CalendarX,
  'calendar-clock': CalendarClock,
  'calendar-heart': CalendarHeart,
  'calendar-range': CalendarRange,
  'calendar-search': CalendarSearch,
  clock: Clock,
  'clock-1': Clock1,
  'clock-3': Clock3,
  'clock-6': Clock6,
  'clock-9': Clock9,
  'clock-12': Clock12,
  'alarm-clock': AlarmClock,
  'alarm-clock-check': AlarmClockCheck,
  'timer-off': TimerOff,
  'timer-reset': TimerReset,
  history: History,
  watch: Watch,
  sunrise: Sunrise,
  sunset: Sunset,
  cloud: Cloud,
  'cloud-rain': CloudRain,
  'cloud-snow': CloudSnow,
  'cloud-sun': CloudSun,
  'cloud-moon': CloudMoon,
  'cloud-fog': CloudFog,
  wind: Wind,
  snowflake: Snowflake,
  thermometer: Thermometer,
  'thermometer-sun': ThermometerSun,
  umbrella: Umbrella,
  rainbow: Rainbow,
  tornado: Tornado,
  haze: Haze,
  mail: Mail,
  'mail-open': MailOpen,
  'mail-plus': MailPlus,
  'mail-check': MailCheck,
  'mail-x': MailX,
  inbox: Inbox,
  'message-circle-more': MessageCircleMore,
  'message-square-more': MessageSquareMore,
  'message-square-text': MessageSquareText,
  phone: Phone,
  'phone-call': PhoneCall,
  'phone-off': PhoneOff,
  voicemail: Voicemail,
  rss: Rss,
  wifi: Wifi,
  'wifi-off': WifiOff,
  bluetooth: Bluetooth,
  globe: Globe,
  'globe-lock': GlobeLock,
  earth: Earth,
  network: Network,
  server: Server,
  database: Database,
  'cloud-off': CloudOff,
  'hard-drive': HardDrive,
  cpu: Cpu,
  'memory-stick': MemoryStick,
  usb: Usb,
  plug: Plug,
  'plug-zap': PlugZap,
  battery: Battery,
  'battery-charging': BatteryCharging,
  'battery-full': BatteryFull,
  'battery-low': BatteryLow,
  signal: Signal,
  'signal-high': SignalHigh,
  'signal-low': SignalLow,
  antenna: Antenna,
  satellite: Satellite,
  'satellite-dish': SatelliteDish,
  'radio-tower': RadioTower,
  webhook: Webhook,
  code: Code,
  'code-xml': CodeXml,
  terminal: Terminal,
  braces: Braces,
  brackets: Brackets,
  'bug-off': BugOff,
  'git-branch': GitBranch,
  'git-commit-horizontal': GitCommitHorizontal,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  info: Info,
  'triangle-alert': TriangleAlert,
  'octagon-alert': OctagonAlert,
  badge: Badge,
  'badge-check': BadgeCheck,
  'badge-alert': BadgeAlert,
  'badge-info': BadgeInfo,
  'badge-x': BadgeX,
  'badge-plus': BadgePlus,
  'badge-minus': BadgeMinus,
  'badge-dollar-sign': BadgeDollarSign,
  'badge-percent': BadgePercent,
  ban: Ban,
  'circle-check-big': CircleCheckBig,
  loader: Loader,
  'loader-circle': LoaderCircle,
  activity: Activity,
  'heart-pulse': HeartPulse,
  gauge: Gauge,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  'star-half': StarHalf,
  'star-off': StarOff,
  'shield-ellipsis': ShieldEllipsis,
  megaphone: Megaphone,
  siren: Siren,
  construction: Construction,
  'traffic-cone': TrafficCone,
  coins: Coins,
  banknote: Banknote,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  receipt: Receipt,
  'receipt-text': ReceiptText,
  ticket: Ticket,
  'ticket-percent': TicketPercent,
  tickets: Tickets,
  tag: Tag,
  tags: Tags,
  percent: Percent,
  'dollar-sign': DollarSign,
  euro: Euro,
  'pound-sterling': PoundSterling,
  bitcoin: Bitcoin,
  calculator: Calculator,
  scale: Scale,
  'scale-3d': Scale3d,
  weight: Weight,
  'chart-bar': ChartBar,
  'chart-bar-big': ChartBarBig,
  'chart-column': ChartColumn,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'chart-area': ChartArea,
  'chart-no-axes-column': ChartNoAxesColumn,
  'chart-spline': ChartSpline,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  sigma: Sigma,
  pi: Pi,
  infinity: Infinity,
  binary: Binary,
  divide: Divide,
  equal: Equal,
  backpack: Backpack,
  briefcase: Briefcase,
  luggage: Luggage,
  shirt: Shirt,
  magnet: Magnet,
  'lamp-desk': LampDesk,
  bed: Bed,
  sofa: Sofa,
  armchair: Armchair,
  bath: Bath,
  fence: Fence,
  warehouse: Warehouse,
  factory: Factory,
  building: Building,
  'building-2': Building2,
  school: School,
  church: Church,
  hospital: Hospital,
  store: Store,
  landmark: Landmark,
  bus: Bus,
  car: Car,
  truck: Truck,
  'tram-front': TramFront,
  plane: Plane,
  rocket: Rocket,
  ship: Ship,
  sailboat: Sailboat,
  bike: Bike,
  fuel: Fuel,
  'car-front': CarFront,
  cone: Cone,
  cylinder: Cylinder,
  cuboid: Cuboid,
  pyramid: Pyramid,
  torus: Torus,
  'flask-conical': FlaskConical,
  'flask-round': FlaskRound,
  'test-tube': TestTube,
  'test-tubes': TestTubes,
  microscope: Microscope,
  telescope: Telescope,
  dna: Dna,
  atom: Atom,
  orbit: Orbit,
  syringe: Syringe,
  pill: Pill,
  stethoscope: Stethoscope,
  bandage: Bandage,
  cross: Cross,
  recycle: Recycle,
  sprout: Sprout,
  'tree-pine': TreePine,
  'tree-deciduous': TreeDeciduous,
  'tree-palm': TreePalm,
  'mountain-snow': MountainSnow,
}

/** Todos los nombres del catálogo, en orden. */
export const iconNames: string[] = ICON_CATALOG.flatMap((category) => category.icons)

/** Componente de un icono por su nombre (undefined si no está en el catálogo). */
export function iconComponent(name: string | null | undefined): Component | undefined {
  return name ? iconComponents[name] : undefined
}
