// @bgm/ui — librería de componentes base + tokens + utilidades del motor.

export { default as BaseButton } from './components/BaseButton.vue'
export { default as IconButton } from './components/IconButton.vue'
export { default as MotorBadge } from './components/MotorBadge.vue'
export { default as TranslatableInput } from './components/TranslatableInput.vue'
export { default as ImageUpload } from './components/ImageUpload.vue'
export { default as BaseModal } from './components/BaseModal.vue'
export { default as BaseTabs } from './components/BaseTabs.vue'
export { default as BaseToast } from './components/BaseToast.vue'
export { default as ToastContainer } from './components/ToastContainer.vue'
export { default as ConfirmDialog } from './components/ConfirmDialog.vue'
export { createApi, type CreateApiOptions } from './lib/createApi'
export { useToast, type Toast } from './composables/useToast'
export { useConfirm, type ConfirmOptions } from './composables/useConfirm'
